# Catppuccin Mocha palette
source=~/.config/hypr/mocha.conf

background {
  blur_passes=2
  blur_size=6
  color=rgba($crustAlphaff)
}

general {
  grace=3
  hide_cursor=true
}

input-field {
  monitor=
  size=250, 50
  dots_center=true
  dots_size=0.200000
  dots_spacing=0.200000
  fade_on_empty=true
  font_color=rgba($rosewaterAlphaff)
  halign=center
  inner_color=rgba($crustAlpha80)
  outer_color=rgba($rosewaterAlpha39)
  outline_thickness=2
  placeholder_text=
  position=0, 20
  valign=center
}

label {
  monitor=
  color=rgba($rosewaterAlphaff)
  font_family=JetBrainsMono Nerd Font
  font_size=65
  halign=center
  position=0, 300
  text=$TIME
  valign=center
}

label {
  monitor=
  color=rgba($rosewaterAlphaff)
  font_family=JetBrainsMono Nerd Font
  font_size=17
  halign=center
  position=0, 240
  text=cmd[update:5000] date +"%A, %B %d"
  valign=center
}

label {
  monitor=
  color=rgba($rosewaterAlphaff)
  font_family=JetBrainsMono Nerd Font
  font_size=20
  halign=center
  position=0, 50
  text=    $USER
  valign=bottom
}

label {
  monitor=
  color=rgba($rosewaterAlphaff)
  font_family=JetBrainsMono Nerd Font
  font_size=14
  halign=right
  position=-30, 30
  text=$LAYOUT
  valign=bottom
}

